### ISSUE TITLE
Use tuples

### ISSUE THREAD

**Issue by mtemelkov** [ianozsvald/learning_text_transformer_demo#4]
training_inputs and training_outputs can be tuples - faster and safer.
Same for line 48 - do you really need a set?

**Comment by ianozsvald** [comment]
Hi there. Sorry for the slow response, I'm just back from holiday.

Re. tuples - I think users will generally have lists of data for training so I'll stick with the lists. There's no performance implication on this side of the code. 

Re. line 48 - the `set` is there to check that the user is passing in the right verb, really I need to clean up that function, I think I'll turn it into a class and extract it to a new module with better docs so this is clearer.

Thanks for the feedback :-)
